# Generated by Django 6.0.4 on 2026-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationresource',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='operationresource',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
