# Generated by Django 6.0.4 on 2026-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('worker', 'Worker'), ('admin', 'Admin'), ('employee', 'Employee'), ('agronomist', 'Agronomist')], default='employee', max_length=20),
        ),
    ]
