# Generated by Django 6.0.4 on 2026-04-21 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_owner_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgronomistAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agronomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agronomist_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
