# Generated by Django 6.0.4 on 2026-04-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agronomistassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agronomistassignment',
            name='can_view_finances',
            field=models.BooleanField(default=False),
        ),
    ]
