# Generated by Django 6.0.4 on 2026-04-25 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_resource_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='season',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to=settings.AUTH_USER_MODEL),
        ),
    ]
