# Generated by Codex on 2026-04-26

from django.db import migrations


def backfill_season_owners(apps, schema_editor):
    Season = apps.get_model("core", "Season")
    FieldCrop = apps.get_model("core", "FieldCrop")

    for season in Season.objects.filter(owner__isnull=True):
        owner_ids = list(
            FieldCrop.objects.filter(season=season)
            .order_by("field__owner_id")
            .values_list("field__owner_id", flat=True)
            .distinct()
        )
        if not owner_ids:
            continue

        first_owner_id = owner_ids[0]
        season.owner_id = first_owner_id
        season.save(update_fields=["owner"])

        for owner_id in owner_ids[1:]:
            owner_season, _ = Season.objects.get_or_create(
                owner_id=owner_id,
                name=season.name,
                start_date=season.start_date,
                end_date=season.end_date,
                defaults={"year": season.year},
            )
            FieldCrop.objects.filter(
                season=season,
                field__owner_id=owner_id,
            ).update(season=owner_season)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_season_owner_field"),
    ]

    operations = [
        migrations.RunPython(backfill_season_owners, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="season",
            unique_together={("owner", "name", "start_date", "end_date")},
        ),
    ]
