# Generated by Django 6.0.4 on 2026-04-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_operation_type_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcrop',
            name='status',
            field=models.CharField(choices=[('запланировано', 'Запланировано'), ('активно', 'Активно'), ('собран', 'Собрано')], default='запланировано', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('вода', 'Вода'), ('питательная смесь', 'Питательная смесь'), ('топливо', 'Топливо'), ('семена', 'Семена')], max_length=20),
        ),
    ]
