# Generated by Django 6.0.4 on 2026-05-05 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_agronomistassignment_recommendation_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
